### 1. Transferencia Exitosa por TITULAR (Camino Feliz - 200 OK)
# Ana (Titular) transfiere a Bruno. El flujo continúa normal[cite: 29].
POST http://localhost:8080/api/v1/transacciones/transferir
Content-Type: application/json

{
  "idCliente": "11111111-1111-1111-1111-111111111111",
  "idCuentaOrigen": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
  "idCuentaDestino": "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb",
  "monto": 1500.50
}

### 2. Operación Denegada para ADHERENTE (Debe dar 403 Forbidden)
# Lucas Perez (Adherente) intenta hacer una transferencia.
# Como la operación no es EXTRACCION, lanza OperacionNoPermitidaException[cite: 29].
POST http://localhost:8080/api/v1/transacciones/transferir
Content-Type: application/json

{
  "idCliente": "55555555-5555-5555-5555-555555555555",
  "idCuentaOrigen": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
  "idCuentaDestino": "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb",
  "monto": 1000.00
}

### 3. Validación de Jakarta: Monto Negativo (Debe dar 400 Bad Request)
POST http://localhost:8080/api/v1/transacciones/transferir
Content-Type: application/json

{
  "idCliente": "11111111-1111-1111-1111-111111111111",
  "idCuentaOrigen": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
  "idCuentaDestino": "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb",
  "monto": -500.00
}

### 4. Excepción de Negocio: Saldo Insuficiente (Debe dar 400 Bad Request)
POST http://localhost:8080/api/v1/transacciones/transferir
Content-Type: application/json

{
  "idCliente": "11111111-1111-1111-1111-111111111111",
  "idCuentaOrigen": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
  "idCuentaDestino": "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb",
  "monto": 5000000.00
}

### 5. Excepción de Negocio: Cuenta Inexistente (Debe dar 404 Not Found)
POST http://localhost:8080/api/v1/transacciones/transferir
Content-Type: application/json

{
  "idCliente": "11111111-1111-1111-1111-111111111111",
  "idCuentaOrigen": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
  "idCuentaDestino": "99999999-9999-9999-9999-999999999999",
  "monto": 1000.00
}